### ISSUE TITLE
™ in Pinecast™ logo is illegible

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#10]
<img width="168" alt="screen shot 2016-09-19 at 11 07 05 pm" src="https://cloud.githubusercontent.com/assets/203725/18659187/cfedfb9a-7ebd-11e6-8f3f-91cf3d883cd5.png">

<img width="151" alt="screen shot 2016-09-19 at 11 07 09 pm" src="https://cloud.githubusercontent.com/assets/203725/18659186/cfedc116-7ebd-11e6-9144-0c9a832ce2b1.png">

<img width="266" alt="screen shot 2016-09-19 at 11 06 34 pm" src="https://cloud.githubusercontent.com/assets/203725/18659174/c247ce1c-7ebd-11e6-9d11-420ce70ef8ff.png">

**Comment by mattbasta** [comment]
<img width="46" alt="screen shot 2016-09-20 at 8 47 44 pm" src="https://cloud.githubusercontent.com/assets/279498/18697227/1b4d89e6-7f74-11e6-9f08-e82322a8c0c7.png">

Thanks to the magic of retina, it's legible enough at a small size to do its job. I'd care more if it was there for aesthetic or legal reasons.
