### ISSUE TITLE
Dashboard › Networks tab should have its own URL path/route

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#11]
I should be able to link to the Networks tab on https://pinecast.com/dashboard/. Either from https://pinecast.com/dashboard/networks or https://pinecast.com/dashboard/#networks.

**Comment by mattbasta** [comment]
Should be moved here https://github.com/Pinecast/pinecast/issues

**Comment by cvan** [comment]
Right, good call. My bad.

**Comment by cvan** [comment]
Filed https://github.com/Pinecast/pinecast/issues/115
