### ISSUE TITLE
Minify CSS, HTML, JS

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#15]
Either with a build step or use CloudFlare's AutoMinify™ which is amazing.

**Comment by mattbasta** [comment]
I have some settings on CF turned on already, but the CSS and HTML are small enough that minification makes almost no difference with H2 and gzip.

**Comment by cvan** [comment]
which settings do you have turned on? yeah, minification is fine with HTTP/2, and I see you got gzip enabled so you cool.
