### ISSUE TITLE
Add a `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#3]

**Comment by mattbasta** [comment]
I thought about this all day. I don't hope to get many contributions on this repo, and adding a CONTRIBUTING.md might make it seem like I'm fishing for PRs. The only reason this repo even exists is a.) it's cool that I can host for free while also making the code open, b.) it's easy to edit on the fly, and c.) it's in the spirit of having a fully open-source company. That's not to say, however, that I'm looking for active engagement on it.

The pinecast/pinecast repo might be a better fit for one, but there's also very little around engaging the OSS community that I've done. I don't have guidelines or preferences or the like for PRs or issues. In the future, this will definitely make more sense.
